### ISSUE TITLE
Exception: merge failed

### ISSUE THREAD

**Issue by mkrizek** [ansible/ansibullbot#1004]
This traceback appeared couple times recently, investigate if there's anything we can do here.

```
2018-08-22 17:00:10,348 INFO starting triage for https://github.com/ansible/ansible/pull/16748
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 290, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 507, in run
    action_meta = self.apply_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1442, in apply_actions
    return super(AnsibleTriage, self).apply_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 322, in apply_actions
    self.execute_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2268, in execute_actions
    super(AnsibleTriage, self).execute_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 439, in execute_actions
    iw.merge()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1244, in merge
    raise Exception('merge failed')
Exception: merge failed
```

**Comment by jctanner** [comment]
Need to start with expanding the exception to include more about the http response.
