### ISSUE TITLE
small_patch: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mkrizek** [ansible/ansibullbot#1085]
```
2018-10-22 07:35:14,574 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 184, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 295, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 463, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1905, in process
    self.meta.update(get_small_patch_facts(iw))
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/small_patch.py", line 22, in get_small_patch_facts
    for commit in iw.get_commits():
TypeError: 'NoneType' object is not iterable
```

**Comment by mkrizek** [comment]
There are more, related to current github issues. Closing.
