### ISSUE TITLE
relocated modules can cause tracebacks in component tools

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1097]
```
2018-11-12 15:41:28,164 INFO starting triage for https://github.com/ansible/ansible/issues/14681
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 184, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 295, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 295, in run
    self.component_matcher.update(email_cache=self.module_indexer.emails_cache)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/component_tools.py", line 124, in update
    self.index_files()
  File "/home/ansibot/ansibullbot/ansibullbot/utils/component_tools.py", line 211, in index_files
    u'authors': ME.authors,
  File "/home/ansibot/ansibullbot/ansibullbot/utils/extractors.py", line 440, in authors
    self._AUTHORS = self.get_module_authors()
  File "/home/ansibot/ansibullbot/ansibullbot/utils/extractors.py", line 455, in get_module_authors
    lines = to_text(self.filedata).split(u'\n')
  File "/home/ansibot/ansibullbot/ansibullbot/utils/extractors.py", line 433, in filedata
    with open(self.filepath, 'rb') as f:
IOError: [Errno 2] No such file or directory: u'/home/ansibot/.ansibullbot/cache/ansible.checkout/lib/ansible/modules/messaging/rabbitmq_global_parameter.py'
```

**Comment by mkrizek** [comment]
This has been fixed in https://github.com/ansible/ansibullbot/commit/efed3205e22aec70c74102db6cd240f3f4573815.
