### ISSUE TITLE
Bot traceback due to commented out author line

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#1106]
PR https://github.com/ansible/ansible/pull/49228 introduced a commented out author entry which appears to have caused the bot to traceback:

```
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 234, in __init__
    commits=not self.ignore_module_commits
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 119, in __init__
    self.update(force=True)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 126, in update
    self.parse_metadata()
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 148, in parse_metadata
    self.get_ansible_modules()
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 387, in get_ansible_modules
    self.set_maintainers()
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 711, in set_maintainers
    authors = self.get_module_authors(mfile)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 857, in get_module_authors
    github_ids = self.extract_github_id(author)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/moduletools.py", line 865, in extract_github_id
    if u'ansible core team' in author.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

Removing the commented out author in https://github.com/ansible/ansible/commit/8987a647e3f08215792167a3dd0041572c848f19 appears to have resolved the issue.

**Comment by mattclay** [comment]
Once this is fixed we may want to restore the author entry that was removed.
