### ISSUE TITLE
TemplateRuntimeError: no test named 'equalto'

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1129]
```Sentry APP [7:38 AM]
TemplateRuntimeError - jinja2.environment in call_test
no test named 'equalto'
ANSIBULLBOT-19 via AlertToday at 7:38 AM
```

```
2018-12-16 12:38:47,528 INFO starting triage for https://github.com/ansible/ansible/pull/49974
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 51, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 47, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 196, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 307, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 472, in run
    self.create_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 945, in create_actions
    boilerplate=u'community_shipit_notify'
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 322, in render_boilerplate
    comment = template.render(**tvars)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ansibot/ansibullbot/templates/community_shipit_notify.j2", line 1, in top-level template code
    {{ '@' + (community_usernames | reject("equalto", submitter) | join(' @')) }}
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 318, in do_join
    return text_type(d).join(imap(text_type, value))
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 931, in _select_or_reject
    if modfunc(func(transfunc(item))):
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 925, in 
    name, item, args, kwargs)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 438, in call_test
    raise TemplateRuntimeError('no test named %r' % name)
TemplateRuntimeError: no test named 'equalto'
2018-12-16 12:38:51,098 INFO Starting new HTTPS connection (1): sentry.io
2018-12-16 12:38:51,347 DEBUG "POST /api/1336908/store/ HTTP/1.1" 200 41
```

**Comment by jctanner** [comment]
```
[centos@ansibullbot ~]$ rpm -q python-jinja2
python-jinja2-2.7.2-2.el7.noarch
[centos@ansibullbot ~]$ cat jtest.py 
#!/usr/bin/env python

from jinja2 import Environment

TEMPLATE = '''{{ '@' + (community_usernames | reject("equalto", submitter) | join(' @')) }}'''
env = Environment()
template = env.from_string(TEMPLATE)

print(template.render(community_usernames=['foo', 'bar'], submitter='bar'))

[centos@ansibullbot ~]$ python jtest.py 
Traceback (most recent call last):
  File "jtest.py", line 9, in <module>
    print(template.render(community_usernames=['foo', 'bar'], submitter='bar'))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 318, in do_join
    return text_type(d).join(imap(text_type, value))
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 931, in _select_or_reject
    if modfunc(func(transfunc(item))):
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 925, in <lambda>
    name, item, args, kwargs)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 438, in call_test
    raise TemplateRuntimeError('no test named %r' % name)
jinja2.exceptions.TemplateRuntimeError: no test named 'equalto'
```

**Comment by jctanner** [comment]
```
(ansibot_py3) [jtanner@jtw530 ansibullbot.1129]$ pip2 show jinja2 | egrep ^Version
Version: 2.10
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(ansibot_py3) [jtanner@jtw530 ansibullbot.1129]$ python2 jtest.py 
@foo

```
