### ISSUE TITLE
historywrapper traceback

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1207]
```
2019-06-24 14:07:50,061 DEBUG https://api.github.com:443 "GET /repos/ansible/ansible/pulls/57353/reviews HTTP/1.1" 200 None
2019-06-24 14:07:50,248 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 465, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2064, in build_history
    iw.history.merge_reviews(iw.reviews)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 740, in merge_reviews
    event[u'actor'] = review[u'user'][u'login']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jctanner** [comment]
The review seems to be missing the user. Nothing we can do here except skip processing it.
```
(Epdb) pp review
{u'_links': {u'html': {u'href': u'https://github.com/ansible/ansible/pull/57353#pullrequestreview-249085292'},
             u'pull_request': {u'href': u'https://api.github.com/repos/ansible/ansible/pulls/57353'}},
 u'author_association': u'NONE',
 u'body': u'',
 u'commit_id': u'7294f93cbcafd6cc3fe11da02816e29ef1d3dd65',
 u'html_url': u'https://github.com/ansible/ansible/pull/57353#pullrequestreview-249085292',
 u'id': 249085292,
 u'node_id': u'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjQ5MDg1Mjky',
 u'pull_request_url': u'https://api.github.com/repos/ansible/ansible/pulls/57353',
 u'state': u'COMMENTED',
 u'submitted_at': u'2019-06-13T01:00:07Z',
 u'user': None}
```
