### ISSUE TITLE
need to catch ReadTimeout exceptions in the ratelimit decorator

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1214]
```
2019-06-27 01:14:41,017 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [repo_full_name] [4140]
2019-06-27 01:14:41,017 DEBUG @pullrequest.get_pullrequest #34277
2019-06-27 01:14:41,017 DEBUG https://api.github.com/rate_limit
2019-06-27 01:14:41,019 DEBUG Starting new HTTPS connection (1): api.github.com:443
2019-06-27 01:14:41,107 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2019-06-27 01:14:41,111 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_pullrequest] [4140]
2019-06-27 01:14:56,130 ERROR HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
2019-06-27 01:14:56,304 DEBUG Starting new HTTPS connection (1): sentry.io:443
2019-06-27 01:14:56,427 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 409, in run
    ua = to_text(iw.pullrequest.updated_at.isoformat())
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 877, in pullrequest
    self._pr = self.repo.get_pullrequest(self.number)
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 125, in inner
    x = fn(*args, **kwargs)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/ghapiwrapper.py", line 138, in get_pullrequest
    pr = self.repo.get_pull(number)
  File "/usr/lib/python2.7/site-packages/github/Repository.py", line 2124, in get_pull
    self.url + "/pulls/" + str(number)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 324, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 377, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 401, in __requestRaw
    response = cnx.getresponse()
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 109, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
```

**Comment by jctanner** [comment]
```2019-06-27 12:53:05,966 INFO starting triage for https://github.com/ansible/ansible/pull/40760
2019-06-27 12:53:05,971 DEBUG https://api.github.com/rate_limit
2019-06-27 12:53:05,972 DEBUG Starting new HTTPS connection (1): api.github.com:443
2019-06-27 12:53:06,055 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2019-06-27 12:53:06,059 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [repo_full_name] [4814]
2019-06-27 12:53:06,059 DEBUG @pullrequest.get_pullrequest #40760
2019-06-27 12:53:06,063 DEBUG https://api.github.com/rate_limit
2019-06-27 12:53:06,065 DEBUG Starting new HTTPS connection (1): api.github.com:443
2019-06-27 12:53:06,150 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2019-06-27 12:53:06,154 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_pullrequest] [4814]
2019-06-27 12:53:21,173 ERROR HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
2019-06-27 12:53:21,240 DEBUG Starting new HTTPS connection (1): sentry.io:443
2019-06-27 12:53:21,277 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 409, in run
    ua = to_text(iw.pullrequest.updated_at.isoformat())
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 877, in pullrequest
    self._pr = self.repo.get_pullrequest(self.number)
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 125, in inner
    x = fn(*args, **kwargs)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/ghapiwrapper.py", line 138, in get_pullrequest
    pr = self.repo.get_pull(number)
  File "/usr/lib/python2.7/site-packages/github/Repository.py", line 2124, in get_pull
    self.url + "/pulls/" + str(number)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 324, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 377, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 401, in __requestRaw
    response = cnx.getresponse()
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 109, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
```
