### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1247]
```

2019-07-31 12:47:24,351 DEBUG https://api.github.com:443 "GET /repositories/3638964/issues/32294/events?page=2 HTTP/1.1" 403 None
2019-07-31 12:47:24,458 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 466, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2065, in build_history
    iw.history
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1264, in history
    HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 130, in __init__
    self.history = self.process()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 677, in process
    events = self.issue.events
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 201, in events
    self._events = self.get_events()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 214, in get_events
    if not dd.get(u'created_at') and dd.get(u'submitted_at'):
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by jctanner** [comment]
I think this is happening when the events/timeline api is returning a ratelimit error and the new requestor function doesn't trigger the ratelimit exception.

**Comment by jctanner** [comment]
```
2019-07-31 14:42:28,317 DEBUG https://api.github.com:443 "GET /repositories/3638964/issues/27179/events?page=3 HTTP/1.1" 403 None
2019-07-31 14:42:28,445 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 466, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2065, in build_history
    iw.history
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1264, in history
    HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 130, in __init__
    self.history = self.process()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 677, in process
    events = self.issue.events
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 201, in events
    self._events = self.get_events()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 214, in get_events
    if not dd.get(u'created_at') and dd.get(u'submitted_at'):
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by jctanner** [comment]
still broken 

```
2019-07-31 19:15:40,273 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 466, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2065, in build_history
    iw.history
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1264, in history
    HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 130, in __init__
    self.history = self.process()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 677, in process
    events = self.issue.events
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 201, in events
    self._events = self.get_events()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 214, in get_events
    if not dd.get(u'created_at') and dd.get(u'submitted_at'):
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by jctanner** [comment]
```
2019-07-31 21:25:16,608 DEBUG https://api.github.com/rate_limit
2019-07-31 21:25:16,610 DEBUG Starting new HTTPS connection (1): api.github.com:443
2019-07-31 21:25:16,702 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2019-07-31 21:25:16,706 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_issue] [4354]
2019-07-31 21:25:16,712 DEBUG Starting new HTTPS connection (1): api.github.com:443
2019-07-31 21:25:16,868 DEBUG https://api.github.com:443 "GET /repos/ansible/ansible/issues/43641 HTTP/1.1" 304 0
2019-07-31 21:25:16,869 INFO starting triage for https://github.com/ansible/ansible/issues/43641
2019-07-31 21:25:16,872 INFO !/home/ansibot/.ansibullbot/cache/ansible/ansible/issues/43641/history.pickle
2019-07-31 21:25:16,872 INFO empty history cache, rebuilding
2019-07-31 21:25:16,872 INFO !/home/ansibot/.ansibullbot/cache/ansible/ansible/issues/43641/history.pickle
2019-07-31 21:25:16,873 DEBUG /home/ansibot/.ansibullbot/cache/ansible/ansible/issues/43641/events_data.json
2019-07-31 21:25:16,873 ERROR documentation_url is not a dict
```
