### ISSUE TITLE
traceback on get_commit_login

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1265]
```
2019-08-23 13:34:38,546 INFO commit detected, resetting shipit tallies
2019-08-23 13:34:38,547 INFO ganeshrn shipit [rebuild_merge]
2019-08-23 13:34:38,547 INFO total shipits: 2
2019-08-23 13:34:38,575 INFO https://github.com/ansible/ansible/pull/59967 sushma-alethea association: CONTRIBUTOR
2019-08-23 13:34:38,576 DEBUG _labels == False
2019-08-23 13:34:38,585 DEBUG qcounter: 75
2019-08-23 13:34:38,585 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_labels] [3217]
2019-08-23 13:34:38,585 DEBUG automerge community support test failed
2019-08-23 13:34:38,590 INFO dump meta to /home/ansibot/.ansibullbot/cache/ansible/ansible/issues/59967/meta.json
2019-08-23 13:34:38,619 INFO RECEIVER: POST to http://127.0.0.1:5001/metadata
2019-08-23 13:34:38,621 DEBUG Starting new HTTP connection (1): 127.0.0.1:5001
2019-08-23 13:34:38,725 DEBUG http://127.0.0.1:5001 "POST /metadata?repo=ansible&user=ansible&number=59967 HTTP/1.1" 200 27
2019-08-23 13:34:38,726 INFO RECEIVER: replaced result
2019-08-23 13:34:38,727 INFO url: https://github.com/ansible/ansible/pull/59967
2019-08-23 13:34:38,727 INFO title: icx: new module icx_linkagg
2019-08-23 13:34:38,727 INFO component[f]: lib/ansible/modules/network/icx/icx_linkagg.py
2019-08-23 13:34:38,727 INFO component[f]: test/units/modules/network/icx/fixtures/lag_running_config.txt
2019-08-23 13:34:38,727 INFO component[f]: test/units/modules/network/icx/test_icx_linkagg.py
2019-08-23 13:34:38,737 DEBUG qcounter: 76
2019-08-23 13:34:38,737 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_commit_login] [3216]
2019-08-23 13:34:38,813 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 203, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 314, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 513, in run
    action_meta = self.apply_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1518, in apply_actions
    return super(AnsibleTriage, self).apply_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 346, in apply_actions
    self.execute_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2355, in execute_actions
    super(AnsibleTriage, self).execute_actions(iw, actions)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 463, in execute_actions
    iw.merge()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1436, in merge
    logins = sorted(set(self.committer_logins))
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1415, in committer_logins
    self.committer_logins.append(self.get_commit_login(commit))
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 170, in inner
    raise Exception('unhandled message type')
Exception: unhandled message type
```

**Comment by jctanner** [comment]
```2020-01-24 17:46:28,159 ERROR Uncaught exception
Traceback (most recent call last):
  File "./triage_ansible.py", line 45, in <module>
    main()
  File "./triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
    self.run()
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/ansibullbot/triagers/ansible.py", line 503, in run
    self.process(iw)
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/ansibullbot/triagers/ansible.py", line 2092, in process
    logins = sorted(set(iw.committer_logins))
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1405, in committer_logins
    self.committer_logins.append(self.get_commit_login(commit))
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/ansibullbot/decorators/github.py", line 112, in inner
    return fn(*args, **kwargs)
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1377, in get_commit_login
    login = cdata['author']['login']
TypeError: 'NoneType' object is not subscriptable
```
