### ISSUE TITLE
traceback on 

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1266]
```2019-08-23 15:45:56,034 DEBUG https://api.github.com:443 "GET /repos/ansible/ansible/issues/17714/reactions HTTP/1.1" 200 None
2019-08-23 15:45:56,044 DEBUG qcounter: 84
2019-08-23 15:45:56,044 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.historywrapper.HistoryWrapper'>] [_raw_data_from_event] [3208]
2019-08-23 15:45:56,051 DEBUG qcounter: 85
2019-08-23 15:45:56,051 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.historywrapper.HistoryWrapper'>] [_raw_data_from_event] [3207]
2019-08-23 15:45:56,058 DEBUG qcounter: 86
2019-08-23 15:45:56,058 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.historywrapper.HistoryWrapper'>] [_raw_data_from_event] [3206]
2019-08-23 15:45:56,064 DEBUG qcounter: 87
2019-08-23 15:45:56,064 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.historywrapper.HistoryWrapper'>] [_raw_data_from_event] [3205]
2019-08-23 15:45:56,071 DEBUG qcounter: 88
2019-08-23 15:45:56,071 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.historywrapper.HistoryWrapper'>] [_raw_data_from_event] [3204]
2019-08-23 15:45:56,159 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 177, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 288, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 498, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2097, in build_history
    iw.history
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1277, in history
    HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 132, in __init__
    self.history = self.process()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 763, in process
    processed_events = self._fix_history_tz(processed_events)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 894, in _fix_history_tz
    if not x[u'created_at'].tzinfo:
AttributeError: 'unicode' object has no attribute 'tzinfo'
```
17714

**Comment by jctanner** [comment]
```
2019-08-23 15:56:27,503 DEBUG https://api.github.com:443 "GET /repos/ansible/ansible/issues/61203/timeline HTTP/1.1" 200 None
2019-08-23 15:56:27,517 DEBUG qcounter: 91
2019-08-23 15:56:27,517 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_reactions] [3201]
2019-08-23 15:56:27,703 DEBUG https://api.github.com:443 "GET /repos/ansible/ansible/issues/61203/reactions HTTP/1.1" 200 None
2019-08-23 15:56:27,797 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 177, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 288, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 498, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2097, in build_history
    iw.history
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1277, in history
    HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 155, in __init__
    self.history = self.process()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 763, in process
    processed_events = self._fix_history_tz(processed_events)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 894, in _fix_history_tz
    if not x[u'created_at'].tzinfo:
AttributeError: 'unicode' object has no attribute 'tzinfo'
```

**Comment by jctanner** [comment]
````
2019-08-23 15:56:27,703 DEBUG https://api.github.com:443 "GET /repos/ansible/ansible/issues/61203/reactions HTTP/1.1" 200 None
2019-08-23 15:56:27,797 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 177, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 288, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 498, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2097, in build_history
    iw.history
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1277, in history
    HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 155, in __init__
    self.history = self.process()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 763, in process
    processed_events = self._fix_history_tz(processed_events)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 894, in _fix_history_tz
    if not x[u'created_at'].tzinfo:
AttributeError: 'unicode' object has no attribute 'tzinfo'
```
