### ISSUE TITLE
PY36: TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1310]
```
2020-04-27 19:16:53,154 DEBUG 29864 github.py:inner:139 ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_comments] [4727]
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./triage_ansible_mp.py", line 50, in run_triage_worker
    triager.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 551, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2095, in process
    self.meta,
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/needs_contributor.py", line 22, in get_needs_contributor_facts
    if u'!needs_contributor' in event[u'body']:
TypeError: a bytes-like object is required, not 'str'
```

```
2020-04-27 19:16:51,689 DEBUG 29867 github.py:inner:139 ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_comments] [4739]
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./triage_ansible_mp.py", line 50, in run_triage_worker
    triager.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 551, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2133, in process
    self.meta.update(get_bot_status_facts(iw, self.module_indexer, core_team=self.ansible_core_team, bot_names=self.BOTNAMES))
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/botstatus.py", line 7, in get_bot_status_facts
    if u'bot_status' in ev[u'body']:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansibullbot/pull/1311

**Comment by webknjaz** [comment]
FYI there's also compat that you could use: https://github.com/ansible/ansibullbot/blob/master/ansibullbot/_text_compat.py
