### ISSUE TITLE
removed method was still in use

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1312]
```
2020-04-29 14:29:25,178 INFO 4411 ansible.py:run:458 starting triage for https://github.com/ansible/ansible/issues/67555
2020-04-29 14:29:25,233 INFO 4411 historywrapper.py:__init__:134 use cached history
2020-04-29 14:29:25,263 ERROR 4411 triage_ansible.py:handle_exception:31 Uncaught exception
Traceback (most recent call last):
  File "./triage_ansible.py", line 45, in <module>
    main()
  File "./triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 161, in start
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 551, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2026, in process
    self.get_ansible_version_by_issue(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2504, in get_ansible_version_by_issue
    for comment in iw.current_comments:
AttributeError: 'IssueWrapper' object has no attribute 'current_comments'
Sentry is attempting to send 1 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Comment by mkrizek** [comment]
Fixed in https://github.com/ansible/ansibullbot/pull/1313
