### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by mkrizek** [ansible/ansibullbot#1355]
```
2020-05-19 15:15:40,037 INFO 5900 ansible.py:run:452 starting triage for https://github.com/ansible/ansible/pull/69154
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 158, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 269, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 545, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2027, in process
    self.valid_labels
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/component_matching.py", line 64, in get_component_match_facts
    CM_MATCHES = component_matcher.match(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/component_tools.py", line 481, in match
    files=iw.files
  File "/home/ansibot/ansibullbot/ansibullbot/utils/component_tools.py", line 551, in match_components
    elif self.gitrepo.existed(fn):
  File "/home/ansibot/ansibullbot/ansibullbot/utils/git_tools.py", line 258, in existed
    lrev = self.get_last_rev_for_file(filepath)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/git_tools.py", line 247, in get_last_rev_for_file
    (rc, so, se) = run_command(cmd)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/systemtools.py", line 15, in run_command
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

```
2020-05-19 15:15:41,692 DEBUG 5900 connectionpool.py:_new_conn:813 Starting new HTTPS connection (1): sentry.io:443
2020-05-19 15:15:41,874 DEBUG 5900 connectionpool.py:_make_request:393 https://sentry.io:443 "POST /api/1336908/store/ HTTP/1.1" 200 41

2020-05-19 15:18:13,487 INFO 1758 ansible.py:run:452 starting triage for https://github.com/ansible/ansible/pull/69040
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 158, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 269, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 545, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2007, in process
    self.version_indexer.version_by_date(iw.created_at)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/version_tools.py", line 425, in version_by_date
    (rc, so, se) = run_command(cmd)
  File "/home/ansibot/ansibullbot/ansibullbot/utils/systemtools.py", line 15, in run_command
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by mkrizek** [comment]
Not just related to get_last_rev_for_file.

**Comment by mkrizek** [comment]
```
[centos@ansibullbot ~]$ sudo ps -eo pid,ppid,cmd:150,%mem,%cpu --sort=-%mem | head
  PID  PPID CMD                                                       %MEM     %CPU
30879 30868 /usr/bin/python /home/ansibot/ansibullbot/scripts/ansibot_receiver.py    82.2  0.7
```
