### ISSUE TITLE
py3 detection based on traceback paths

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#308]
https://github.com/ansible/ansible/issues/20818
```
Traceback (most recent call last):
  File "/tmp/ansible_ckjkjhx8/ansible_module_service.py", line 1552, in <module>
    main()
  File "/tmp/ansible_ckjkjhx8/ansible_module_service.py", line 1508, in main
    service.get_service_status()
  File "/tmp/ansible_ckjkjhx8/ansible_module_service.py", line 575, in get_service_status
    rc, status_stdout, status_stderr = self.service_control()
  File "/tmp/ansible_ckjkjhx8/ansible_module_service.py", line 899, in service_control
    rc_state, stdout, stderr = self.execute_command("%s %s %s" % (svc_cmd, self.action, arguments), daemonize=True)
  File "/tmp/ansible_ckjkjhx8/ansible_module_service.py", line 262, in execute_command
    return json.loads(data)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansibullbot/pull/339
