### ISSUE TITLE
cannot allocate memory traceback

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#381]
```
2017-02-21 12:33:57,257 DEBUG Starting new HTTPS connection (1): api.github.com                                                                                        [251/1882]
2017-02-21 12:33:57,349 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2017-02-21 12:33:57,356 DEBUG ratelimited call #1 [<class 'lib.wrappers.issuewrapper.IssueWrapper'>] [get_template_data] [4875]
Traceback (most recent call last):
  File "./triage.py", line 114, in <module>
    main()
  File "./triage.py", line 110, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 285, in start
    self.loop()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 324, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 488, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 1394, in process
    self.get_ansible_version_by_issue(iw)
  File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 485, in get_ansible_version_by_issue
    self.issue.instance.created_at
  File "/home/ansibot/ansibullbot/lib/utils/version_tools.py", line 475, in ansible_version_by_date
    aversion = self.ansible_version_by_commit(acommit)
  File "/home/ansibot/ansibullbot/lib/utils/version_tools.py", line 395, in ansible_version_by_commit
    (rc, so, se) = run_command(cmd)
  File "/home/ansibot/ansibullbot/lib/utils/systemtools.py", line 9, in run_command
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/ansibot/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/ansibot/anaconda2/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by jctanner** [comment]
the ec2 instance should be sufficient to ignore this old error.
