### ISSUE TITLE
timeout on webscraper

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#439]
```
2017-03-24 00:48:08,724 INFO getting issue objs for ansible/ansible-modules-extras
2017-03-24 00:48:08,851 DEBUG GET https://api.github.com/repos/ansible/ansible-modules-extras/issues?since=2017-03-24T00%3A40%3A40Z {'Authorization': 'Basic
 (login and password removed)', 'User-Agent': 'PyGithub/Python'} null ==> 200 {'status': '200 OK', 'content-length': '2', 'x-github-media-type': 'github.v3;
 format=json', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'", 'access-control-expose-headers': 'ETag, Link, X-GitHub-
OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'A330:25
A12:BC47B7:F1AE18:58D46CC8', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'vary': 'Accept, Authorization, Cookie, X-GitHub-O
TP, Accept-Encoding', 'x-ratelimit-remaining': '4848', 'server': 'GitHub.com', 'date': 'Fri, 24 Mar 2017 00:48:08 GMT', 'x-xss-protection': '1; mode=block',
 'etag': '"0e684afc216dad81df25149fba4ec5e0"', 'x-served-by': '075bb2f6b7031ca3c0e69edb17939fae', 'cache-control': 'private, max-age=60, s-maxage=60', 'x-ra
telimit-limit': '5000', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'x-frame-options': 'deny', 'x-ratelimit-reset
': '1490317035'} []
2017-03-24 00:48:08,858 INFO getting last issue number for ansible/ansible-modules-extras
2017-03-24 00:48:08,978 DEBUG https://github.com/ansible/ansible-modules-extras/issues?q=sort%3Aupdated-desc
2017-03-24 00:48:08,981 DEBUG Starting new HTTPS connection (1): github.com
Traceback (most recent call last):
  File "./triage.py", line 111, in <module>
    main()
  File "./triage.py", line 107, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 287, in start
    self.loop()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 326, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 338, in run
    self.collect_repos()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 1372, in collect_repos
    last_number = self.gws.get_last_number(repo)
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 108, in get_last_number
    issues = self.get_issue_summaries(repo_url)
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 136, in get_issue_summaries
    rr = self._request_url(url)
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 511, in _request_url
    rr = requests.get(url, headers=headers)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ansible/ansible-modules-extras/issues
?q=sort%3Aupdated-desc (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8c5a851050>: Failed to est
ablish a new connection: [Errno -2] Name or service not known',))
```

**Comment by jctanner** [comment]
should have been fixed in https://github.com/ansible/ansibullbot/pull/426/commits/b10fac9d535038e5e256264d2b7b705757947da1
