### ISSUE TITLE
shippable run traceback

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#452]
https://github.com/ansible/ansible/pull/23061

```
2017-03-29 14:33:50,503 DEBUG Starting new HTTPS connection (1): api.github.com
2017-03-29 14:33:50,599 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2017-03-29 14:33:50,603 DEBUG ratelimited call #1 [<class 'lib.wrappers.issuewrapper.IssueWrapper'>] [get_labels] [4908]
2017-03-29 14:33:50,605 DEBUG https://api.shippable.com/runs/17552
2017-03-29 14:33:50,607 DEBUG Starting new HTTPS connection (1): api.shippable.com
2017-03-29 14:33:50,775 DEBUG https://api.shippable.com:443 "GET /runs/17552 HTTP/1.1" 404 156
2017-03-29 14:33:50,778 ERROR RC: 404
2017-03-29 14:33:52,781 DEBUG https://api.shippable.com/runs/17552
2017-03-29 14:33:52,789 DEBUG Starting new HTTPS connection (1): api.shippable.com
2017-03-29 14:33:53,012 DEBUG https://api.shippable.com:443 "GET /runs/17552 HTTP/1.1" 404 156
2017-03-29 14:33:53,018 ERROR RC: 404
Traceback (most recent call last):
  File "./triage.py", line 113, in <module>
    main()
  File "./triage.py", line 109, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 291, in start
    self.loop()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 330, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 494, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 1686, in process
    get_shippable_run_facts(iw, self.meta, shippable=self.SR)
  File "/home/ansibot/ansibullbot/lib/triagers/plugins/needs_revision.py", line 469, in get_shippable_run_facts
    vinfo = sh.info_for_last_ci_verified_run()
  File "/home/ansibot/ansibullbot/lib/wrappers/historywrapper.py", line 726, in info_for_last_ci_verified_run
    run_info = self.history[run_idx]
TypeError: list indices must be integers, not NoneType
```

**Comment by jctanner** [comment]
Fixed by https://github.com/ansible/ansibullbot/pull/453
