### ISSUE TITLE
traceback on shippable api query

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#472]
```
2017-04-07 23:19:10,448 ERROR RC: 404
Traceback (most recent call last):
  File "./triage.py", line 117, in <module>
    main()
  File "./triage.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 292, in start
    self.loop()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 331, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 487, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 1763, in process
    get_shippable_run_facts(iw, self.meta, shippable=self.SR)
  File "/home/ansibot/ansibullbot/lib/triagers/plugins/needs_revision.py", line 468, in get_shippable_run_facts
    filter_paths=['/testresults/ansible-test-.*.json'],
  File "/home/ansibot/ansibullbot/lib/utils/shippable_api.py", line 191, in get_test_results
    commitSha = run_data['commitSha']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jctanner** [comment]
Fixed by https://github.com/ansible/ansibullbot/pull/473
