### ISSUE TITLE
new exeception

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#528]
```
2017-05-22 12:13:45,375 INFO pullrequest_status load pfile
2017-05-22 12:13:45,379 INFO fetching pr status: <date
2017-05-22 12:13:45,382 DEBUG Starting new HTTPS connection (1): api.github.com
2017-05-22 12:13:45,468 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 500 None
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 283, in start
    self.loop()
  File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 765, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 466, in run
    iw.update_pullrequest()
  File "/home/ansibot/ansibullbot/lib/wrappers/defaultwrapper.py", line 675, in update_pullrequest
    self.get_pullrequest_status(force_fetch=True)
  File "/home/ansibot/ansibullbot/lib/wrappers/defaultwrapper.py", line 741, in get_pullrequest_status
    jdata = self._fetch_api_url(surl)
  File "/home/ansibot/ansibullbot/lib/decorators/github.py", line 71, in inner
    rl = get_rate_limit()
  File "/home/ansibot/ansibullbot/lib/decorators/github.py", line 36, in get_rate_limit
    return rr.json()
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/ansibot/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ansibot/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jctanner** [comment]
Haven't seen this in a while.
