### ISSUE TITLE
requests IncompleteRead traceback

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#578]
```
  File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 763, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 477, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 1815, in process
    self.meta,
  File "/home/ansibot/ansibullbot/lib/triagers/plugins/needs_revision.py", line 81, in get_needs_revision_facts
    www_summary = triager.gws.get_single_issue_summary(rfn, iw.number)
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 248, in get_single_issue_summary
    rr = self._request_url(url)
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 616, in _request_url
    rr = requests.get(url, headers=headers)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/models.py", line 706, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3634 bytes read, 5611 more expected)', IncompleteRead(3634 bytes read, 5611 more expected))
```

**Comment by jctanner** [comment]
```
2017-06-20 23:19:47,588 DEBUG https://github.com/ansible/ansible-modules-core/issues?page=2&q=sort%3Aupdated-desc
2017-06-20 23:19:47,590 DEBUG Starting new HTTPS connection (1): github.com
2017-06-20 23:19:47,918 DEBUG https://github.com:443 "GET /ansible/ansible-modules-core/issues?page=2&q=sort%3Aupdated-desc HTTP/1.1" 200 None
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 278, in start
    self.loop()
  File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 763, in loop
    self.run()
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 330, in run
    self.update_issue_summaries(repopath=repopath)
  File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 556, in update_issue_summaries
    cachefile=cachefile
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 161, in get_issue_summaries
    rr = self._request_url(self.baseurl + data['next_page'])
  File "/home/ansibot/ansibullbot/lib/utils/webscraper.py", line 616, in _request_url
    rr = requests.get(url, headers=headers)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/ansibot/anaconda2/lib/python2.7/site-packages/requests/models.py", line 706, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3634 bytes read, 5966 more expected)', IncompleteRead(3634 bytes read, 5966 more expected))
```

**Comment by jctanner** [comment]
I think we can ignore this now that we're using graphql.
