### ISSUE TITLE
unhandled rate limiting in get_reviews

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#600]
```
2017-06-27 01:50:39,035 DEBUG ratelimited call #1 [<class 'lib.wrappers.issuewrapper.IssueWrapper'>] [get_comments] [0]
2017-06-27 01:50:39,045 DEBUG Starting new HTTPS connection (1): api.github.com
2017-06-27 01:50:39,194 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2017-06-27 01:50:39,198 DEBUG ratelimited call #1 [<class 'lib.wrappers.issuewrapper.IssueWrapper'>] [get_reviews] [0]
2017-06-27 01:50:39,331 DEBUG GET https://api.github.com/repos/ansible/ansible/pulls/18557/reviews {'Authorization': 'token (oauth token removed)', 'Accept': 'application/vnd.github.black-cat-preview+json', 'User-Agent': 'PyGithub/Python'} null ==> 403 {'status': '403 Forbidden', 'x-accepted-oauth-scopes': 'repo', 'content-length': '119', 'x-github-media-type': 'github.v3; param=black-cat-preview; format=json', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'", 'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'ADCA:0D82:A887539:C8B88AE:5951F22F', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-oauth-scopes': 'public_repo, read:org, repo:status, repo_deployment', 'x-ratelimit-remaining': '0', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'x-runtime-rack': '0.016967', 'date': 'Tue, 27 Jun 2017 05:50:39 GMT', 'x-frame-options': 'deny', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'x-xss-protection': '1; mode=block', 'x-ratelimit-reset': '1498542827'} {"message":"API rate limit exceeded for ansibot.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/lib/triagers/defaulttriager.py", line 281, in start
    self.run()
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/lib/triagers/ansible.py", line 478, in run
    self.build_history(iw)
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/lib/triagers/ansible.py", line 1954, in build_history
    iw.history.merge_reviews(iw.reviews)
  File "/home/jtanner/workspace/github/jctanner/ansibullbot/lib/wrappers/historywrapper.py", line 629, in merge_reviews
    event['id'] = review['id']
TypeError: string indices must be integers
```

**Comment by jctanner** [comment]
Haven't seen this in a while.
