### ISSUE TITLE
historywrapper + reviews typerror

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#650]
```
2017-07-18 15:38:45,853 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_reviews] [4250]
2017-07-18 15:38:45,995 DEBUG GET https://api.github.com/repos/ansible/ansible/pulls/26982/reviews {'Authorization': 'token (oauth token removed)', 'Accept': 'application/vnd.github.black-cat-preview+json', 'User-Agent': 'PyGithub/Python'} null ==> 422 {'status': '422 Unprocessable Entity', 'x-accepted-oauth-scopes': '', 'content-length': '230', 'x-github-media-type': 'github.v3; param=black-cat-preview; format=json', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'", 'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'A512:4FE5:B2AAC4:17EAB61:596E2B85', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-oauth-scopes': 'public_repo, read:org, repo:status, repo_deployment', 'x-ratelimit-remaining': '4249', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'x-runtime-rack': '0.083852', 'date': 'Tue, 18 Jul 2017 15:38:45 GMT', 'x-frame-options': 'deny', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'x-xss-protection': '1; mode=block', 'x-ratelimit-reset': '1500394674'} {"message":"Validation Failed","errors":["Could not resolve to a node with the global id of 'MDExOlB1bGxSZXF1ZXN0MTMxMTIwMjg3'."],"documentation_url":"https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request"}
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 485, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1997, in build_history
    iw.history.merge_reviews(iw.reviews)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/historywrapper.py", line 629, in merge_reviews
    event['id'] = review['id']
TypeError: string indices must be integers
```

**Comment by jctanner** [comment]
This happened again today when github went down.

**Comment by mkrizek** [comment]
We track tracebacks in sentry now.
