### ISSUE TITLE
str + int concatenation traceback

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#655]
```
2017-07-18 20:36:22,399 INFO dump meta to /home/ansibot/.ansibullbot/cache/ansible/ansible/issues/27009/meta.json                                          │
Traceback (most recent call last):                                                                                                                         │
  File "./triage_ansible.py", line 117, in <module>                                                                                                        │
    main()                                                                                                                                                 │
  File "./triage_ansible.py", line 113, in main                                                                                                            │
    AnsibleTriage(args).start()                                                                                                                            │
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start                                                              │
    self.loop()                                                                                                                                            │
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop                                                               │
    self.run()                                                                                                                                             │
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 503, in run                                                                       │
    self.save_meta(iw, self.meta)                                                                                                                          │
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 636, in save_meta                                                                 │
    dmeta                                                                                                                                                  │
  File "/home/ansibot/ansibullbot/ansibullbot/utils/receiver_client.py", line 21, in post_to_receiver                                                      │
    receiverurl += C.DEFAULT_RECEIVER_PORT                                                                                                                 │
TypeError: cannot concatenate 'str' and 'int' objects 
```

**Comment by jctanner** [comment]
exposed after merging https://github.com/ansible/ansibullbot/issues/654
