### ISSUE TITLE
read operation timed out

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#660]
```
2017-07-19 13:37:13,972 INFO finished triage for https://github.com/ansible/ansible/issues/11024
2017-07-19 13:37:13,972 INFO starting triage for https://github.com/ansible/ansible-modules-core/issues/5825
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 416, in run
    mod_repo = (iw.repo_full_name in MREPOS)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 664, in repo_full_name
    return self.repo.repo.full_name
  File "/usr/lib/python2.7/site-packages/github/Repository.py", line 252, in full_name
    self._completeIfNotSet(self._full_name)
  File "/usr/lib/python2.7/site-packages/github/GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "/usr/lib/python2.7/site-packages/github/GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "/usr/lib/python2.7/site-packages/github/GithubObject.py", line 260, in __complete
    self._url.value
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/lib/python2.7/site-packages/github/Requester.py", line 279, in __requestRaw
    response = cnx.getresponse()
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 759, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: ('The read operation timed out',)
```

**Comment by jctanner** [comment]
duplicate of https://github.com/ansible/ansibullbot/issues/678
