### ISSUE TITLE
json decode errors again

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#663]
```

2017-07-20 16:54:04,977 ERROR No JSON object could be decoded
2017-07-20 16:54:04,978 ERROR breakpoint!
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 485, in run
    iw.update_pullrequest()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 726, in update_pullrequest
    self.get_reviews()
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 173, in inner
    import epdb; epdb.st()
ImportError: No module named epdb
[ansibot@ansibullbot ansibullbot]$
```

**Comment by mkrizek** [comment]
We track tracebacks in sentry now.
