### ISSUE TITLE
traceback fetching issue

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#682]
```
2017-07-27 15:58:06,859 INFO starting triage for https://github.com/ansible/ansible/pull/26733
2017-07-27 15:58:06,860 INFO Starting new HTTPS connection (1): api.github.com
2017-07-27 15:58:06,944 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-07-27 15:58:06,948 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [load_update_fetch] [3132]
2017-07-27 15:58:17,057 ERROR 'Issue' object has no attribute 'get_raw_data'
2017-07-27 15:58:17,058 ERROR 'Issue' object has no attribute 'get_raw_data'
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 412, in run
    file_indexer=self.file_indexer
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 127, in __init__
    self.raw_data_issue = self.load_update_fetch('raw_data', obj='issue')
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 175, in inner
    raise Exception('no data in exception')
Exception: no data in exception
```

**Comment by jctanner** [comment]
Haven't seen this one in a while.
