### ISSUE TITLE
waffling on PRs with many commits

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#685]
https://github.com/ansible/ansible/pull/24292

**Comment by jctanner** [comment]
```
2017-07-29 11:31:21,541 INFO mergeable_state is unstable
2017-07-29 11:31:21,541 INFO needs_rebase is True
2017-07-29 11:31:21,541 INFO needs_revision is True
2017-07-29 11:31:21,541 INFO ready_for_review is None
2017-07-29 11:31:21,662 INFO Starting new HTTPS connection (1): api.github.com
2017-07-29 11:31:21,738 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-07-29 11:31:21,742 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_template_data] [4175]
2017-07-29 11:31:21,886 ERROR "ci_verified" label is waffling on https://github.com/ansible/ansible/pull/24292
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 507, in run
    self.create_actions()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1299, in create_actions
    raise LabelWafflingError(msg)
ansibullbot.errors.LabelWafflingError: "ci_verified" label is waffling on https://github.com/ansible/ansible/pull/24292
```

**Comment by jctanner** [comment]
resolved.
