### ISSUE TITLE
exception in get_raw_data

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#689]
```
2017-08-01 17:43:58,397 INFO starting triage for https://github.com/ansible/ansible/issues/27594
2017-08-01 17:43:58,398 INFO Starting new HTTPS connection (1): api.github.com
2017-08-01 17:43:58,480 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-08-01 17:43:58,483 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [load_update_fetch] [4242]
2017-08-01 17:44:08,538 ERROR 'Issue' object has no attribute 'get_raw_data'
2017-08-01 17:44:08,538 ERROR 'Issue' object has no attribute 'get_raw_data'
Traceback (most recent call last):
  File "./triage_ansible.py", line 117, in <module>
    main()
  File "./triage_ansible.py", line 113, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 279, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 764, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 412, in run
    file_indexer=self.file_indexer
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 127, in __init__
    self.raw_data_issue = self.load_update_fetch('raw_data', obj='issue')
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 175, in inner
    raise Exception('no data in exception')
Exception: no data in exception
```

**Comment by gundalow** [comment]
Going to assume this has been fixed
