### ISSUE TITLE
Exception: unknown supported_by type

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#707]
```
2017-08-16 14:29:21,016 WARNING re-fetch[1] PR#23464 because mergeable state is unknown
2017-08-16 14:29:21,017 INFO Starting new HTTPS connection (1): api.github.com
2017-08-16 14:29:21,092 DEBUG "GET /rate_limit HTTP/1.1" 200 None


2017-08-16 14:29:24,197 INFO total shipits: 0
2017-08-16 14:29:24,197 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 130, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 126, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 324, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 809, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 514, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1927, in process
    self.meta.update(self.get_review_facts(iw, self.meta))
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2196, in get_review_facts
    raise Exception('unknown supported_by type')
Exception: unknown supported_by type
```

**Comment by jctanner** [comment]
```
--
2017-08-16 13:44:03,196 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_template_data] [4498]
2017-08-16 13:44:03,198 INFO total shipits: 1
2017-08-16 13:44:03,198 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 130, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 126, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 324, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 809, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 514, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1927, in process
    self.meta.update(self.get_review_facts(iw, self.meta))
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2196, in get_review_facts
    raise Exception('unknown supported_by type')
Exception: unknown supported_by type
--
2017-08-16 14:29:24,195 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_template_data] [2646]
2017-08-16 14:29:24,197 INFO total shipits: 0
2017-08-16 14:29:24,197 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 130, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 126, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 324, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 809, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 514, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1927, in process
    self.meta.update(self.get_review_facts(iw, self.meta))
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2196, in get_review_facts
    raise Exception('unknown supported_by type')
Exception: unknown supported_by type
--
2017-08-16 14:32:33,042 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_template_data] [2466]
2017-08-16 14:32:33,044 INFO total shipits: 1
2017-08-16 14:32:33,044 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 130, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 126, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 324, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 809, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 514, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1927, in process
    self.meta.update(self.get_review_facts(iw, self.meta))
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2196, in get_review_facts
    raise Exception('unknown supported_by type')
Exception: unknown supported_by type
```
