### ISSUE TITLE
shipit waffling

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#722]
```
2017-08-19 16:57:43,251 ERROR "shipit" label is waffling on https://github.com/ansible/ansible/pull/26099
2017-08-19 16:57:43,252 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 131, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 127, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 326, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 811, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 526, in run
    self.create_actions()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1334, in create_actions
    raise LabelWafflingError(msg)
LabelWafflingError: "shipit" label is waffling on https://github.com/ansible/ansible/pull/26099
```

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansibullbot/pull/725
