### ISSUE TITLE
"packaging/" should not match "lib/ansible/modules/packaging/os/xbps.py"

### ISSUE THREAD

**Issue by pilou-** [ansible/ansibullbot#765]
`packaging` was recently added in `.github/BOTMETA.yml` (#28956) but now `packaging/` matches `lib/ansible/modules/packaging/os/xbps.py`.

<pre>
2017-09-11 21:54:12,641 ERROR Uncaught exception
Traceback (most recent call last):
  File "./triage_ansible.py", line 137, in <module>
    main()
  File "./triage_ansible.py", line 133, in main
    AnsibleTriage(args).start()
  File "ansibullbot/triagers/ansible.py", line 244, in __init__
    self.module_indexer = ModuleIndexer(gh_client=self.gqlc)
  File "ansibullbot/utils/moduletools.py", line 65, in __init__
    self.update(force=True)
  File "ansibullbot/utils/moduletools.py", line 71, in update
    self.parse_metadata()
  File "ansibullbot/utils/moduletools.py", line 100, in parse_metadata
    self.get_ansible_modules()
  File "ansibullbot/utils/moduletools.py", line 335, in get_ansible_modules
    self.set_maintainers()
  File "ansibullbot/utils/moduletools.py", line 565, in set_maintainers
    if 'ignored' in self.botmeta['files'][best_match]:
</pre>

<pre>
(Pdb) best_match
'packaging/'
(Pdb) v['filepath']
'lib/ansible/modules/packaging/os/xbps.py'
(Pdb) k
'lib/ansible/modules/packaging/os/xbps.py'
(Pdb) self.botmeta['files'][best_match] is None
True
</pre>

**Comment by pilou-** [comment]
Fixed by #766.
