### ISSUE TITLE
Traceback in _collect_repo

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#792]
```
2017-10-19 15:07:58,746 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_repo] [4858]
2017-10-19 15:07:58,746 INFO getting issue objs for ansible/ansible-modules-extras
2017-10-19 15:07:58,748 DEBUG ansible/ansible-modules-extras issues pagecount:0 nodecount: 0
2017-10-19 15:07:58,749 INFO Starting new HTTPS connection (1): api.github.com
2017-10-19 15:07:58,816 DEBUG "POST /graphql HTTP/1.1" 200 929
2017-10-19 15:07:58,818 ERROR 'data'
2017-10-19 15:07:58,818 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 140, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 136, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 218, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 347, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 327, in run
    self.collect_repos()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1505, in collect_repos
    self._collect_repo(repo)
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 175, in inner
    raise Exception('no data in exception')
Exception: no data in exception
```

**Comment by mkrizek** [comment]
We track tracebacks in sentry now.
