### ISSUE TITLE
No handler found for uri [/repos/ansible/ansible/issues/26816] and method [GET]

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#805]
```
2017-10-25 17:33:32,213 DEBUG dump /home/ansibot/.ansibullbot/cache/ansible/ansible/issues/26827/issue.pickle
2017-10-25 17:33:32,217 INFO starting triage for https://github.com/ansible/ansible/issues/26827
2017-10-25 17:33:32,218 INFO skipping: no changes since last run
2017-10-25 17:33:32,218 INFO finished triage for https://github.com/ansible/ansible/issues/26827
2017-10-25 17:33:32,219 INFO Starting new HTTPS connection (1): api.github.com
2017-10-25 17:33:32,296 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-10-25 17:33:32,298 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_issue] [2878]
2017-10-25 17:33:32,444 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/26824 {'If-None-Match': '"137e9c5aa561a01c986da86abe357f53"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Fri, 08 Sep 2017 04:10:03 GMT'} null ==> 304 {'status': '304 Not Modified', 'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"', 'x-ratelimit-remaining': '2878', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'", 'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'DE7C:13F8:4E6F80:B793B6:59F0CAEC', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'vary': 'Accept, Authorization, Cookie, X-GitHub-OTP', 'server': 'GitHub.com', 'last-modified': 'Sun, 08 Oct 2017 04:10:14 GMT', 'x-ratelimit-limit': '5000', 'x-runtime-rack': '0.064909', 'etag': '"137e9c5aa561a01c986da86abe357f53"', 'cache-control': 'private, max-age=60, s-maxage=60', 'date': 'Wed, 25 Oct 2017 17:33:32 GMT', 'access-control-allow-origin': '*', 'content-type': 'application/octet-stream', 'x-frame-options': 'deny', 'x-ratelimit-reset': '1508953813'}
2017-10-25 17:33:32,445 INFO starting triage for https://github.com/ansible/ansible/issues/26824
2017-10-25 17:33:32,447 INFO skipping: no changes since last run
2017-10-25 17:33:32,447 INFO finished triage for https://github.com/ansible/ansible/issues/26824
2017-10-25 17:33:32,448 INFO Starting new HTTPS connection (1): api.github.com
2017-10-25 17:33:32,738 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-10-25 17:33:32,741 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_issue] [2878]
2017-10-25 17:33:32,804 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/26816 {'If-None-Match': '"725816bb23bd7bb0b19843120bda3068"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Fri, 08 Sep 2017 04:10:03 GMT'} null ==> 400 {'x-github-request-id': 'DE80:13F8:4E6FA4:B79415:59F0CAEC', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/26816] and method [GET]
2017-10-25 17:33:32,806 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/26816] and method [GET]'}
2017-10-25 17:33:32,807 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 140, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 136, in main
    AnsibleTriage(args).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 218, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 347, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 343, in run
    for issue in item[1]['issues']:
  File "/home/ansibot/ansibullbot/ansibullbot/utils/iterators.py", line 25, in next
    issue = self.repo.get_issue(thisnum)
  File "/home/ansibot/ansibullbot/ansibullbot/decorators/github.py", line 178, in inner
    raise Exception('no data in exception')
Exception: no data in exception
```

**Comment by jctanner** [comment]
```
[root@ansibullbot log]# fgrep 'No handler found for uri' ansibullbot.log       
2017-10-25 17:33:32,804 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/26816 {'If-None-Match': '"725816bb23bd7bb0b19843120bda3068"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Fri, 08 Sep 2017 04:10:03 GMT'} null ==> 400 {'x-github-request-id': 'DE80:13F8:4E6FA4:B79415:59F0CAEC', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/26816] and method [GET]
2017-10-25 17:33:32,806 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/26816] and method [GET]'}                                 
2017-10-25 17:34:12,080 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/26776 {'If-None-Match': '"4b37f2c8e3219845d1ac0f80df61bce7"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Wed, 16 Aug 2017 17:52:38 GMT'} null ==> 400 {'x-github-request-id': 'DF5A:13F7:326F0B:6F2F38:59F0CB14', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/26776] and method [GET]
2017-10-25 17:34:12,082 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/26776] and method [GET]'}                                 
2017-10-25 17:35:30,322 DEBUG GET https://api.github.com/repos/ansible/ansible/pulls/26459 {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} null ==> 400 {'x-github-request-id': 'E1BC:13F9:4D8251:A27845:59F0CB62', 'content-length': '78', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/pulls/26459] and method [GET]
2017-10-25 17:35:30,324 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/pulls/26459] and method [GET]'}                                  
2017-10-25 17:38:13,123 DEBUG GET https://api.github.com/repos/ansible/ansible/pulls/25257 {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} null ==> 400 {'x-github-request-id': 'E4C2:13F9:4DC7E2:A30CE8:59F0CC05', 'content-length': '78', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/pulls/25257] and method [GET]
2017-10-25 17:38:13,126 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/pulls/25257] and method [GET]'}                                  
2017-10-25 17:39:14,830 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/24985 {'If-None-Match': '"c4c8ab06073b5e68ad8805db5fe17e5d"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Tue, 19 Sep 2017 22:38:19 GMT'} null ==> 400 {'x-github-request-id': 'E6C6:13F7:32C242:6FEAE8:59F0CC42', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/24985] and method [GET]
2017-10-25 17:39:14,832 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/24985] and method [GET]'}                                 
2017-10-25 17:48:09,336 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/18299 {'If-None-Match': '"4f36de9ec7020de5de01148d1b2f8e74"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Thu, 17 Aug 2017 04:10:20 GMT'} null ==> 400 {'x-github-request-id': '95CE:13F9:4EC18B:A51E64:59F0CE59', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/18299] and method [GET]
2017-10-25 17:48:09,338 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/18299] and method [GET]'}                                 
2017-10-25 17:49:31,378 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/17337 {'If-None-Match': '"0ae3a73eba1e48358cfb6474dd93cbf7"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Thu, 07 Sep 2017 15:30:03 GMT'} null ==> 400 {'x-github-request-id': '98CC:13F8:500D31:BB6C0F:59F0CEAB', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/17337] and method [GET]
2017-10-25 17:49:31,380 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/17337] and method [GET]'}                                 
2017-10-25 17:52:15,759 DEBUG GET https://api.github.com/repos/ansible/ansible/issues/14171 {'If-None-Match': '"5edc1dba357ce1fd9a67065269a41a41"', 'User-Agent': 'PyGithub/Python', 'Authorization': 'token (oauth token removed)', 'If-Modified-Since': 'Mon, 28 Aug 2017 17:42:25 GMT'} null ==> 400 {'x-github-request-id': 'A088:13F7:339B38:71D44B:59F0CF4F', 'content-length': '79', 'content-type': 'text/plain; charset=UTF-8'} No handler found for uri [/repos/ansible/ansible/issues/14171] and method [GET]
2017-10-25 17:52:15,761 ERROR 400 {'data': 'No handler found for uri [/repos/ansible/ansible/issues/14171] and method [GET]'} 
```

**Comment by gundalow** [comment]
Closing as https://github.com/ansible/ansibullbot/pull/806 is merged
