### ISSUE TITLE
ci_verified label waffling

### ISSUE THREAD

**Issue by samdoran** [ansible/ansibullbot#812]
Waffling on [26388](https://github.com/ansible/ansible/pull/26388)

```
telimit-remaining': '4243', 'x-github-media-type': 'github.v3; format=json', 'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'D3DE:7E3E:2965EA2:6345769:5A070C79', 'last-modified': 'Thu, 09 Nov 2017 11:44:44 GMT', 'date': 'Sat, 11 Nov 2017 14:43:05 GMT', 'access-control-allow-origin': '*', 'content-security-policy': "default-src 'none'", 'x-runtime-rack': '0.027035', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'x-frame-options': 'deny', 'content-type': 'application/json; charset=utf-8', 'x-ratelimit-reset': '1510413815'} {"sha":"b45a46587543111f20fa6767b9c4fb895d34e1c9","url":"https://api.github.com/repos/ansible/ansible/git/commits/b45a46587543111f20fa6767b9c4fb895d34e1c9","html_url":"https://github.com/ansible/ansible/commit/b45a46587543111f20fa6767b9c4fb895d34e1c9","author":{"name":"talzur","email":"tal@spotinst.com","date":"2017-11-09T11:44:44Z"},"committer":{"name":"talzur","email":"tal@spotinst.com","date":"2017-11-09T11:44:44Z"},"tree":{"sha":"e9d14872d577cb5ac7d9601507ce572ac9a3b367","url":"https://api.github.com/repos/ansible/ansible/git/trees/e9d14872d577cb5ac7d9601507ce572ac9a3b367"},"message":"module/spotinst/spotinst_aws_elastigroup: formatting","parents":[{"sha":"62bf0a932f32d075a31a2a4dc8f778a48431e66d","url":"https://api.github.com/repos/ansible/ansible/git/commits/62bf0a932f32d075a31a2a4dc8f778a48431e66d","html_url":"https://github.com/ansible/ansible/commit/62bf0a932f32d075a31a2a4dc8f778a48431e66d"}],"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}}
2017-11-11 14:43:05,895 INFO Starting new HTTPS connection (1): api.github.com
2017-11-11 14:43:05,972 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-11-11 14:43:05,976 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_commit_message] [4243]
2017-11-11 14:43:05,983 INFO mergeable_state is unstable
2017-11-11 14:43:05,983 INFO needs_rebase is False
2017-11-11 14:43:05,983 INFO needs_revision is True
2017-11-11 14:43:05,983 INFO ready_for_review is None
2017-11-11 14:43:05,983 INFO shippable: get 43679 run data
2017-11-11 14:43:05,984 INFO shippable: https://api.shippable.com/runs?providerIds=562dbd9710c5980d003b0451&subscriptionOrgNames=ansible&projectNames=ansible&runNumbers=43679
2017-11-11 14:43:05,992 DEBUG _labels == False
2017-11-11 14:43:05,994 INFO Starting new HTTPS connection (1): api.github.com
2017-11-11 14:43:06,092 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-11-11 14:43:06,096 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_labels] [4243]
2017-11-11 14:43:06,096 INFO shippable: https://api.shippable.com/runs?providerIds=562dbd9710c5980d003b0451&subscriptionOrgNames=ansible&projectNames=ansible&runNumbers=43679
2017-11-11 14:43:06,101 DEBUG PRs with needs_revision or needs_rebase label do not get shipits
2017-11-11 14:43:06,115 INFO https://github.com/ansible/ansible/pull/26388 talzur association: FIRST_TIME_CONTRIBUTOR
2017-11-11 14:43:06,124 ERROR "ci_verified" label is waffling on https://github.com/ansible/ansible/pull/26388
2017-11-11 14:43:06,125 ERROR Uncaught exception
Traceback (most recent call last):
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in <module>
   main()
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
   AnsibleTriage().start()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 179, in start
   self.loop()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 289, in loop
   self.run()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 430, in run
   self.create_actions(iw, actions)
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1243, in create_actions
   raise LabelWafflingError(msg)
LabelWafflingError: "ci_verified" label is waffling on https://github.com/ansible/ansible/pull/26388
```

**Comment by gundalow** [comment]
Possibly related https://github.com/ansible/ansible/pull/33986 changes `lib/ansible/module_utils/facts/system/platform.py` and Shippable failed with
`lib/ansible/module_utils/facts/system/platform.py:100:23: W601 .has_key() is deprecated, use 'in'`

Wonder if the `ci_verified` detection code is broken

**Comment by jctanner** [comment]
can be worked around via:

```
!waffling ci_verified
```
