### ISSUE TITLE
reviews - TypeError: can't compare datetime.datetime to bool

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#822]
```
2017-11-27 13:04:28,710 INFO ansible version: 2.5.0
2017-11-27 13:04:28,712 INFO Starting new HTTPS connection (1): api.github.com
2017-11-27 13:04:28,982 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-11-27 13:04:28,985 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [load_update_fetch] [3786]
2017-11-27 13:04:28,997 INFO Starting new HTTPS connection (1): api.github.com
2017-11-27 13:04:29,099 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2017-11-27 13:04:29,102 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [pullrequest_raw_data] [3786]
2017-11-27 13:04:29,102 INFO pullrequest_status load pfile
2017-11-27 13:04:29,103 INFO ci_state == success
2017-11-27 13:04:29,103 INFO mergeable_state == clean
2017-11-27 13:04:29,103 ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 179, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 289, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 435, in run
    self.process(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1716, in process
    self.meta,
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/needs_revision.py", line 233, in get_needs_revision_facts
    if ready_for_review is None or event['created_at'] > ready_for_review:
TypeError: can't compare datetime.datetime to bool
```

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/pull/28792
