### ISSUE TITLE
stack trace in compenent_matching.py — list index out of range

### ISSUE THREAD

**Issue by samdoran** [ansible/ansibullbot#829]
```
es/cloud/smartos/imgadm.py', 'lib/ansible/modules/cloud/smartos/smartos_image_facts.py', 'lib/ansible/modules/cloud/smartos/vmadm.py', 'lib/ansible/modules/cloud/softlayer/__init__.py', 'lib/ansible/modules/cloud/softlayer/sl_vm.py', 'lib/ansible/modules/cloud/univention/__init__.py', 'lib/ansible/modules/cloud/univention/udm_dns_record.py', 'lib/ansible/modules/cloud/univention/udm_dns_zone.py', 'lib/ansible/modules/cloud/univention/udm_group.py', 'lib/ansible/modules/cloud/univention/udm_share.py', 'lib/ansible/modules/cloud/univention/udm_user.py', 'lib/ansible/modules/cloud/vmware/__init__.py', 'lib/ansible/modules/cloud/vmware/vca_fw.py', 'lib/ansible/modules/cloud/vmware/vca_nat.py', 'lib/ansible/modules/cloud/vmware/vca_vapp.py', 'lib/ansible/modules/cloud/vmware/vcenter_license.py', 'lib/ansible/modules/cloud/vmware/vmware_cfg_backup.py', 'lib/ansible/modules/cloud/vmware/vmware_cluster.py', 'lib/ansible/modules/cloud/vmware/vmware_datacenter.py', 'lib/ansible/modules/cloud/vmware/vmware_dns_config.py', 'lib/ansible/modules/cloud/vmware/vmware_dvs_host.py', 'lib/ansible/modules/cloud/vmware/vmware_dvs_portgroup.py', 'lib/ansible/modules/cloud/vmware/vmware_dvswitch.py', 'lib/ansible/modules/cloud/vmware/vmware_guest.py', 'lib/ansible/modules/cloud/vmware/vmware_guest_facts.py', 'lib/ansible/modules/cloud/vmware/vmware_guest_find.py', 'lib/ansible/modules/cloud/vmware/vmware_guest_powerstate.py', 'lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py', 'lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py', 'lib/ansible/modules/cloud/vmware/vmware_host.py', 'lib/ansible/modules/cloud/vmware/vmware_host_facts.py', 'lib/ansible/modules/cloud/vmware/vmware_local_user_manager.py', 'lib/ansible/modules/cloud/vmware/vmware_maintenancemode.py', 'lib/ansible/modules/cloud/vmware/vmware_migrate_vmk.py', 'lib/ansible/modules/cloud/vmware/vmware_portgroup.py', 'lib/ansible/modules/cloud/vmware/vmware_resource_pool.py', 'lib/ansible/modules/cloud/vmware/vmware_target_canonical_facts.py', 'lib/ansible/modules/cloud/vmware/vmware_vm_facts.py', 'lib/ansible/modules/cloud/vmware/vmware_vm_shell.py', 'lib/ansible/modules/cloud/vmware/vmware_vm_vss_dvs_migrate.py', 'lib/ansible/modules/cloud/vmware/vmware_vmkernel.py', 'lib/ansible/modules/cloud/vmware/vmware_vmkernel_ip_config.py', 'lib/ansible/modules/cloud/vmware/vmware_vmotion.py', 'lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py', 'lib/ansible/modules/cloud/vmware/vmware_vswitch.py', 'lib/ansible/modules/cloud/vmware/vsphere_copy.py', 'lib/ansible/modules/cloud/vmware/vsphere_guest.py', 'lib/ansible/modules/cloud/vultr/__init__.py', 'lib/ansible/modules/cloud/webfaction/__init__.py', 'lib/ansible/modules/cloud/webfaction/webfaction_app.py', 'lib/ansible/modules/cloud/webfaction/webfaction_db.py', 'lib/ansible/modules/cloud/webfaction/webfaction_domain.py', 'lib/ansible/modules/cloud/webfaction/webfaction_mailbox.py', 'lib/ansible/modules/cloud/webfaction/webfaction_site.py']
2017-12-05 14:57:37,177 ERROR Uncaught exception
Traceback (most recent call last):
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in <module>
   main()
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
   AnsibleTriage().start()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 179, in start
   self.loop()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 289, in loop
   self.run()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 435, in run
   self.process(iw)
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1696, in process
   self.valid_labels
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/component_matching.py", line 69, in get_component_match_facts
   CM_MATCHES = reconcile_component_commands(iw, component_matcher, CM_MATCHES)
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/component_matching.py", line 196, in reconcile_component_commands
   filen = line.split()[1]
IndexError: list index out of range
```

**Comment by jctanner** [comment]
```
[root@ansibullbot log]# fgrep -e "starting bot" -e 'starting triage' ansibullbot.log | fgrep -B1 'starting bot'
2017-12-04 21:18:42,155 INFO starting bot
--
2017-12-04 21:43:05,193 INFO starting triage for https://github.com/ansible/ansible/pull/31046
2017-12-04 21:45:25,992 INFO starting bot
--
2017-12-04 23:18:31,397 INFO starting triage for https://github.com/ansible/ansible/issues/15321
2017-12-04 23:23:51,951 INFO starting bot
--
2017-12-05 14:08:31,493 INFO starting triage for https://github.com/ansible/ansible/issues/33581
2017-12-05 14:08:34,294 INFO starting bot
--
2017-12-05 14:10:55,418 INFO starting triage for https://github.com/ansible/ansible/issues/33448
2017-12-05 14:10:58,613 INFO starting bot
--
2017-12-05 14:54:35,043 INFO starting triage for https://github.com/ansible/ansible/issues/33581
2017-12-05 14:54:37,363 INFO starting bot
--
2017-12-05 14:57:35,698 INFO starting triage for https://github.com/ansible/ansible/issues/33448
2017-12-05 14:57:38,379 INFO starting bot
--
2017-12-05 15:52:36,594 INFO starting triage for https://github.com/ansible/ansible/issues/33581
2017-12-05 15:52:38,115 INFO starting bot
--
2017-12-05 15:55:16,622 INFO starting triage for https://github.com/ansible/ansible/issues/33448
2017-12-05 15:55:20,366 INFO starting bot
--
2017-12-05 16:45:48,764 INFO starting triage for https://github.com/ansible/ansible/issues/33581
2017-12-05 16:45:51,113 INFO starting bot
--
2017-12-05 16:48:14,059 INFO starting triage for https://github.com/ansible/ansible/issues/33448
2017-12-05 16:48:16,869 INFO starting bot
--
2017-12-05 17:33:57,649 INFO starting triage for https://github.com/ansible/ansible/issues/33581
2017-12-05 17:33:59,123 INFO starting bot
```
