### ISSUE TITLE
Label waffling on #19475

### ISSUE THREAD

**Issue by samdoran** [ansible/ansibullbot#879]
```
Python'} null ==> 200 {'content-length': '998', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'vary': 'Accept, Authorization, Cookie, X-GitHub-OTP', 'x-oauth-scopes': 'public_repo, read:org, repo:status, repo_deployment', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-accepted-oauth-scopes': '', 'etag': '"20f2b3debb1fc58e8bdbf01ce9125e1a"', 'cache-control': 'private, max-age=60, s-maxage=60', 'status': '200 OK', 'x-ratelimit-remaining': '4245', 'x-github-media-type': 'github.v3; format=json', 'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'B8EE:292F:601913:BA7303:5AA0E885', 'last-modified': 'Tue, 06 Mar 2018 09:53:22 GMT', 'date': 'Thu, 08 Mar 2018 07:38:45 GMT', 'access-control-allow-origin': '*', 'content-security-policy': "default-src 'none'", 'x-runtime-rack': '0.029263', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'x-frame-options': 'deny', 'content-type': 'application/json; charset=utf-8', 'x-ratelimit-reset': '1520497658'} {"sha":"52a21d43839a0dc67b44159f498369bc56a7cde6","url":"https://api.github.com/repos/ansible/ansible/git/commits/52a21d43839a0dc67b44159f498369bc56a7cde6","html_url":"https://github.com/ansible/ansible/commit/52a21d43839a0dc67b44159f498369bc56a7cde6","author":{"name":"Nathan Davison","email":"ndavison85@gmail.com","date":"2018-03-06T09:53:22Z"},"committer":{"name":"Nathan Davison","email":"ndavison85@gmail.com","date":"2018-03-06T09:53:22Z"},"tree":{"sha":"9af1e3d9344e9b473c335490397c8ed247ae5213","url":"https://api.github.com/repos/ansible/ansible/git/trees/9af1e3d9344e9b473c335490397c8ed247ae5213"},"message":"Fix doc defaults ..again.","parents":[{"sha":"ce1e24f39d7027ca0967bebc1ef252e65a2428d5","url":"https://api.github.com/repos/ansible/ansible/git/commits/ce1e24f39d7027ca0967bebc1ef252e65a2428d5","html_url":"https://github.com/ansible/ansible/commit/ce1e24f39d7027ca0967bebc1ef252e65a2428d5"}],"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}}
2018-03-08 07:38:45,580 INFO Starting new HTTPS connection (1): api.github.com
2018-03-08 07:38:45,657 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2018-03-08 07:38:45,661 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_commit_message] [4245]
2018-03-08 07:38:45,667 INFO mergeable_state is clean
2018-03-08 07:38:45,667 INFO needs_rebase is False
2018-03-08 07:38:45,667 INFO needs_revision is False
2018-03-08 07:38:45,667 INFO ready_for_review is 2017-04-24 12:15:33+00:00
2018-03-08 07:38:45,712 INFO https://github.com/ansible/ansible/pull/19475 ndavison association: FIRST_TIME_CONTRIBUTOR
2018-03-08 07:38:45,712 DEBUG _labels == False
2018-03-08 07:38:45,713 INFO Starting new HTTPS connection (1): api.github.com
2018-03-08 07:38:45,817 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2018-03-08 07:38:45,821 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_labels] [4245]
2018-03-08 07:38:45,822 ERROR "needs_revision" label is waffling on https://github.com/ansible/ansible/pull/19475
2018-03-08 07:38:45,822 ERROR Uncaught exception
Traceback (most recent call last):
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in <module>
   main()
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
   AnsibleTriage().start()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
   self.loop()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 290, in loop
   self.run()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 446, in run
   self.create_actions(iw, actions)
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1322, in create_actions
   raise LabelWafflingError(msg)
LabelWafflingError: "needs_revision" label is waffling on https://github.com/ansible/ansible/pull/19475
```

```
8-03-08 09:05:52,558 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_commit_parents] [3982]
2018-03-08 09:05:52,757 DEBUG GET https://api.github.com/repos/ansible/ansible/git/commits/52a21d43839a0dc67b44159f498369bc56a7cde6 {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} null ==> 200 {'content-length': '998', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'vary': 'Accept, Authorization, Cookie, X-GitHub-OTP', 'x-oauth-scopes': 'public_repo, read:org, repo:status, repo_deployment', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-accepted-oauth-scopes': '', 'etag': '"20f2b3debb1fc58e8bdbf01ce9125e1a"', 'cache-control': 'private, max-age=60, s-maxage=60', 'status': '200 OK', 'x-ratelimit-remaining': '3981', 'x-github-media-type': 'github.v3; format=json', 'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'A8C0:292F:685CD7:CA0D49:5AA0FCF0', 'last-modified': 'Tue, 06 Mar 2018 09:53:22 GMT', 'date': 'Thu, 08 Mar 2018 09:05:52 GMT', 'access-control-allow-origin': '*', 'content-security-policy': "default-src 'none'", 'x-runtime-rack': '0.042727', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'x-frame-options': 'deny', 'content-type': 'application/json; charset=utf-8', 'x-ratelimit-reset': '1520501334'} {"sha":"52a21d43839a0dc67b44159f498369bc56a7cde6","url":"https://api.github.com/repos/ansible/ansible/git/commits/52a21d43839a0dc67b44159f498369bc56a7cde6","html_url":"https://github.com/ansible/ansible/commit/52a21d43839a0dc67b44159f498369bc56a7cde6","author":{"name":"Nathan Davison","email":"ndavison85@gmail.com","date":"2018-03-06T09:53:22Z"},"committer":{"name":"Nathan Davison","email":"ndavison85@gmail.com","date":"2018-03-06T09:53:22Z"},"tree":{"sha":"9af1e3d9344e9b473c335490397c8ed247ae5213","url":"https://api.github.com/repos/ansible/ansible/git/trees/9af1e3d9344e9b473c335490397c8ed247ae5213"},"message":"Fix doc defaults ..again.","parents":[{"sha":"ce1e24f39d7027ca0967bebc1ef252e65a2428d5","url":"https://api.github.com/repos/ansible/ansible/git/commits/ce1e24f39d7027ca0967bebc1ef252e65a2428d5","html_url":"https://github.com/ansible/ansible/commit/ce1e24f39d7027ca0967bebc1ef252e65a2428d5"}],"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}}
2018-03-08 09:05:52,762 INFO Starting new HTTPS connection (1): api.github.com
2018-03-08 09:05:52,862 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2018-03-08 09:05:52,866 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [get_commit_message] [3981]
2018-03-08 09:05:52,872 INFO mergeable_state is unstable
2018-03-08 09:05:52,872 INFO needs_rebase is False
2018-03-08 09:05:52,872 INFO needs_revision is False
2018-03-08 09:05:52,872 INFO ready_for_review is None
2018-03-08 09:05:52,918 INFO https://github.com/ansible/ansible/pull/19475 ndavison association: FIRST_TIME_CONTRIBUTOR
2018-03-08 09:05:52,928 ERROR "needs_revision" label is waffling on https://github.com/ansible/ansible/pull/19475
2018-03-08 09:05:52,928 ERROR Uncaught exception
Traceback (most recent call last):
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in <module>
   main()
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
   AnsibleTriage().start()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
   self.loop()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 290, in loop
   self.run()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 446, in run
   self.create_actions(iw, actions)
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1322, in create_actions
   raise LabelWafflingError(msg)
LabelWafflingError: "needs_revision" label is waffling on https://github.com/ansible/ansible/pull/19475
```

**Comment by jctanner** [comment]
Corrected with `!waffling` command.
