### ISSUE TITLE
Breakage in add_labels_by_issue_type

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#89]
Works mostly, but then breaks on core/3026:

PR #3026: authorized_key: support --diff
Created at 2016-02-12 11:48:12
Updated at 2016-02-23 16:06:46
Debug: Forced core review, skipping maintainer
Debug: --- START Processing Comments:
Debug: robynbergeron is in botlist: 
Debug: Days since last bot comment: 54
Debug: has core_review
Debug: --- END Processing Comments
Debug: PR is mergeable
Debug: Build state is success
Traceback (most recent call last):
  File "./triage.py", line 743, in <module>
    main()
  File "./triage.py", line 740, in main
    triage.run()
  File "./triage.py", line 681, in run
    self.process()
  File "./triage.py", line 631, in process
    self.add_labels_by_issue_type()
  File "./triage.py", line 322, in add_labels_by_issue_type
    if ("New Module Pull Request" in body or "new_plugin" in self.pull_request.desired_pr_labels):
TypeError: argument of type 'NoneType' is not iterable

**Comment by gregdek** [comment]
Yep, successfully reverted, and that fixed the above issue.
