### ISSUE TITLE
attempting to get rerunbatchid on nonetype

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#939]
```
################################ TRACEBACKS #########################
2018-05-25 15:21:29,699 DEBUG "GET /runs?providerIds=562dbd9710c5980d003b0451&subscriptionOrgNames=ansible&projectNames=ansible&runNumbers=https://app.shippable.com/runs/58cb6ad937380a0800e36940 HTTP/1.1" 400 236
2018-05-25 15:21:29,701 ERROR Uncaught exception
Traceback (most recent call last):
File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in
main()
File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
AnsibleTriage().start()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 290, in loop
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 443, in run
self.process(iw)
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1829, in process
shippable=self.SR
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/needs_revision.py", line 130, in get_needs_revision_facts
ci_date = get_last_shippable_full_run_date(ci_status, shippable)
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/needs_revision.py", line 656, in get_last_shippable_full_run_date
rundata['rerun_batch_id'] = rdata.get('reRunBatchId')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jctanner** [comment]
```
[ansibot@ansibullbot ~]$ fgrep -e "starting triage" -e "2018-05-25 15:21:29,701 ERROR Uncaught exception" /var/log/ansibullbot.log | fgrep -B1 "2018-05-25 15:21:29,701 ERROR Uncaught exception"
2018-05-25 15:21:25,303 INFO starting triage for https://github.com/ansible/ansible/pull/22728
2018-05-25 15:21:29,701 ERROR Uncaught exception
```

**Comment by jctanner** [comment]
Fixed https://github.com/ansible/ansibullbot/pull/940
