### ISSUE TITLE
defaultwrapper.py: turl = sd['target_url']: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by mkrizek** [ansible/ansibullbot#959]
```
2018-06-11 16:36:19,823 INFO starting triage for https://github.com/ansible/ansible/pull/33032
Traceback (most recent call last):
File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
main()
File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
AnsibleTriage().start()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 290, in loop
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 443, in run
self.process(iw)
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1828, in process
shippable=self.SR
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/needs_revision.py", line 159, in get_needs_revision_facts
mstate = iw.mergeable_state
File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1149, in mergeable_state
self.update_pullrequest()
File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 881, in update_pullrequest
self.get_pullrequest_status(force_fetch=True)
File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 951, in get_pullrequest_status
self.log_ci_status(jdata)
File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 992, in log_ci_status
turl = sd['target_url']
TypeError: string indices must be integers
```

**Comment by mkrizek** [comment]
```
2018-10-19 14:40:37,289 ERROR sd = message, type = <type 'unicode'>
2018-10-19 14:40:37,290 ERROR status_data = {u'message': u'Server Error'}, type = <type 'dict'>
```

**Comment by mkrizek** [comment]
```
2020-05-02 08:24:21,182 ERROR 29264 defaultwrapper.py:log_ci_status:917 sd = message, type = <type 'unicode'>
2020-05-02 08:24:21,462 ERROR 29264 defaultwrapper.py:log_ci_status:918 status_data = {u'message': u'We had issues producing the response to your request. Sorry about that. Please try resubmitting your request and contact us if the problem persists.'}, type = <type 'dict'>
2020-05-02 08:24:22,078 ERROR 29264 triage_ansible.py:handle_exception:31 Uncaught exception
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
    AnsibleTriage(args=sys.argv[1:]).start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 158, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 269, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 544, in run
    iw.update_pullrequest()
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 800, in update_pullrequest
    self.get_pullrequest_status(force_fetch=True)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 870, in get_pullrequest_status
    self.log_ci_status(jdata)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 912, in log_ci_status
    turl = sd[u'target_url']
TypeError: string indices must be integers
```
