### ISSUE TITLE
KeyError on 'patch' in small_patch.py

### ISSUE THREAD

**Issue by samdoran** [ansible/ansibullbot#965]
```
wner}{/repo}","subscriptions_url":"https://api.github.com/users/kevein/subscriptions","organizations_url":"https://api.github.com/users/kevein/orgs","repos_url":"https://api.github.com/users/kevein/repos","events_url":"https://api.github.com/users/kevein/events{/privacy}","received_events_url":"https://api.github.com/users/kevein/received_events","type":"User","site_admin":false},"committer":{"login":"kevein","id":916705,"node_id":"MDQ6VXNlcjkxNjcwNQ==","avatar_url":"https://avatars3.githubusercontent.com/u/916705?v=4","gravatar_id":"","url":"https://api.github.com/users/kevein","html_url":"https://github.com/kevein","followers_url":"https://api.github.com/users/kevein/followers","following_url":"https://api.github.com/users/kevein/following{/other_user}","gists_url":"https://api.github.com/users/kevein/gists{/gist_id}","starred_url":"https://api.github.com/users/kevein/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kevein/subscriptions","organizations_url":"https://api.github.com/users/kevein/orgs","repos_url":"https://api.github.com/users/kevein/repos","events_url":"https://api.github.com/users/kevein/events{/privacy}","received_events_url":"https://api.github.com/users/kevein/received_events","type":"User","site_admin":false},"parents":[{"sha":"0f786bdaa9b7ba75c519af5512c516c12849fe07","url":"https://api.github.com/repos/ansible/ansible/commits/0f786bdaa9b7ba75c519af5512c516c12849fe07","html_url":"https://github.com/ansible/ansible/commit/0f786bdaa9b7ba75c519af5512c516c12849fe07"}],"stats":{"total":0,"additions":0,"deletions":0},"files":[{"sha":null,"filename":"contrib/inventory/mdt_dynamic_inventory.py","status":"modified","additions":0,"deletions":0,"changes":0,"blob_url":"https://github.com/ansible/ansible/blob/c7ecf5402a4b375a33437f081b70467cb0f2b011/contrib/inventory/mdt_dynamic_inventory.py","raw_url":"https://github.com/ansible/ansible/raw/c7ecf5402a4b375a33437f081b70467cb0f2b011/contrib/inventory/mdt_dynamic_inventory.py","contents_url":"https://api.github.com/repos/ansible/ansible/contents/contrib/inventory/mdt_dynamic_inventory.py?ref=c7ecf5402a4b375a33437f081b70467cb0f2b011"},{"sha":null,"filename":"contrib/inventory/nsot.py","status":"modified","additions":0,"deletions":0,"changes":0,"blob_url":"https://github.com/ansible/ansible/blob/c7ecf5402a4b375a33437f081b70467cb0f2b011/contrib/inventory/nsot.py","raw_url":"https://github.com/ansible/ansible/raw/c7ecf5402a4b375a33437f081b70467cb0f2b011/contrib/inventory/nsot.py","contents_url":"https://api.github.com/repos/ansible/ansible/contents/contrib/inventory/nsot.py?ref=c7ecf5402a4b375a33437f081b70467cb0f2b011"},{"sha":null,"filename":"contrib/inventory/stacki.py","status":"modified","additions":0,"deletions":0,"changes":0,"blob_url":"https://github.com/ansible/ansible/blob/c7ecf5402a4b375a33437f081b70467cb0f2b011/contrib/inventory/stacki.py","raw_url":"https://github.com/ansible/ansible/raw/c7ecf5402a4b375a33437f081b70467cb0f2b011/contrib/inventory/stacki.py","contents_url":"https://api.github.com/repos/ansible/ansible/contents/contrib/inventory/stacki.py?ref=c7ecf5402a4b375a33437f081b70467cb0f2b011"}]}
2018-06-23 03:40:43,178 ERROR Uncaught exception
Traceback (most recent call last):
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in <module>
   main()
 File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
   AnsibleTriage().start()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 180, in start
   self.loop()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 290, in loop
   self.run()
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 444, in run
   self.process(iw)
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1834, in process
   self.meta.update(get_small_patch_facts(iw))
 File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/small_patch.py", line 30, in get_small_patch_facts
   chunks_in_file_count = len(re.findall(RE_CHUNK, changed_file.raw_data['patch']))
KeyError: 'patch'
```

**Comment by samdoran** [comment]
cc @mkrizek
